import { expect, test } from "@playwright/test"

test("saves placement, finds skills, connects directly, and undoes removal", async ({ page }) => {
  test.setTimeout(120_000)
  const suffix = crypto.randomUUID().slice(0, 8)
  const email = `map-${suffix}@rehearse.local`
  const titles = [`Arrays ${suffix}`, `Hashmaps ${suffix}`]
  await page.goto("/auth/register")
  await page.getByLabel("Name", { exact: true }).fill("Map Test")
  await page.getByLabel("Email", { exact: true }).fill(email)
  await page.getByLabel("Password", { exact: true }).fill("RehearseTest!2026")
  await page.getByRole("button", { name: "Create account", exact: true }).click()
  await expect(page).toHaveURL(/\/auth\/login\?registered=1$/)
  await page.getByLabel("Email address").fill(email)
  await page.getByLabel("Password", { exact: true }).fill("RehearseTest!2026")
  await page.getByRole("button", { name: "Sign in", exact: true }).click()
  await expect(page).toHaveURL(/\/today$/)

  for (const title of titles) {
    await page.goto("/today/new")
    await page.getByLabel("Topic", { exact: true }).fill(title)
    await page.getByRole("button", { name: "Continue", exact: true }).click()
    await expect(page).toHaveURL(/\/sources$/)
  }
  await page.goto("/skills")
  const map = page.getByTestId("skill-constellation")
  const node = map.getByRole("button", { name: new RegExp(`^${titles[0]}:`) })
  const position = () => node.evaluate((element) => ({ left: (element.parentElement as HTMLElement).style.left, top: (element.parentElement as HTMLElement).style.top }))
  const before = await position()
  await node.press("Alt+ArrowRight")
  await expect(page.getByText("Position saved", { exact: true })).toBeVisible()
  const moved = await position()
  expect(moved.left).not.toBe(before.left)
  await page.reload()
  await expect.poll(position).toEqual(moved)

  await map.getByRole("button", { name: "Fit all", exact: true }).click()
  const box = await node.boundingBox()
  if (!box) throw new Error("Skill is not visible after Fit all")
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.down()
  await page.mouse.move(box.x + box.width / 2 + 40, box.y + box.height / 2 + 50, { steps: 8 })
  await page.mouse.up()
  await expect(page.getByText("Position saved", { exact: true })).toBeVisible()
  const dragged = await position()
  expect(dragged).not.toEqual(moved)
  await page.reload()
  await expect.poll(position).toEqual(dragged)

  await map.getByRole("searchbox", { name: "Find a skill" }).fill(titles[0])
  await map.getByRole("button", { name: titles[0], exact: true }).click()
  await map.getByRole("button", { name: "Connect", exact: true }).click()
  await expect(map.getByText(`From ${titles[0]} — choose another skill.`, { exact: true })).toBeVisible()
  await map.getByRole("button", { name: "Use form", exact: true }).click()
  await expect(page.getByLabel("From", { exact: true }).locator("option:checked")).toHaveText(titles[0])
  await map.getByRole("button", { name: "Connect", exact: true }).click()
  await map.getByRole("searchbox", { name: "Find a skill" }).fill(titles[1])
  await map.getByRole("button", { name: titles[1], exact: true }).click()
  await expect(map.getByText(`${titles[0]} connected to ${titles[1]}.`, { exact: true })).toBeVisible()
  const remove = page.getByRole("button", { name: /^Remove:.*is related to/ })
  await expect(remove).toHaveCount(1)
  await remove.click()
  await expect(remove).toHaveCount(0)
  await page.getByRole("button", { name: "Undo removal", exact: true }).click()
  await expect(remove).toHaveCount(1)
  await page.reload()
  await page.getByText("Manage connections", { exact: true }).click()
  await expect(remove).toHaveCount(1)

  for (const width of [320, 390]) {
    await page.setViewportSize({ width, height: 844 })
    await expect(map.getByRole("button", { name: "Fit all", exact: true })).not.toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(await page.locator(".constellation-stage").evaluate((stage) => stage.getBoundingClientRect().height >= stage.querySelector(".constellation-node-list")!.getBoundingClientRect().height)).toBe(true)
  }
})
